// Pioza Launcher
// Copyright (c) 2025 DashoGames
// Licensed under the MIT License - see LICENSE file for details

#pragma once

static const char* SNI_INTROSPECTION_XML = 
    "<!DOCTYPE node PUBLIC \"-//freedesktop//DTD D-BUS Object Introspection 1.0//EN\" "
    "\"http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd\">\n"
    "<node>\n"
    "  <interface name=\"org.freedesktop.DBus.Introspectable\">\n"
    "    <method name=\"Introspect\">\n"
    "      <arg name=\"data\" direction=\"out\" type=\"s\"/>\n"
    "    </method>\n"
    "  </interface>\n"
    "  <interface name=\"org.freedesktop.DBus.Properties\">\n"
    "    <method name=\"Get\">\n"
    "      <arg name=\"interface\" direction=\"in\" type=\"s\"/>\n"
    "      <arg name=\"propname\" direction=\"in\" type=\"s\"/>\n"
    "      <arg name=\"value\" direction=\"out\" type=\"v\"/>\n"
    "    </method>\n"
    "    <method name=\"GetAll\">\n"
    "      <arg name=\"interface\" direction=\"in\" type=\"s\"/>\n"
    "      <arg name=\"props\" direction=\"out\" type=\"a{sv}\"/>\n"
    "    </method>\n"
    "  </interface>\n"
    "  <interface name=\"org.kde.StatusNotifierItem\">\n"
    "    <method name=\"Activate\">\n"
    "      <arg name=\"x\" direction=\"in\" type=\"i\"/>\n"
    "      <arg name=\"y\" direction=\"in\" type=\"i\"/>\n"
    "    </method>\n"
    "    <method name=\"ContextMenu\">\n"
    "      <arg name=\"x\" direction=\"in\" type=\"i\"/>\n"
    "      <arg name=\"y\" direction=\"in\" type=\"i\"/>\n"
    "    </method>\n"
    "    <method name=\"Scroll\">\n"
    "      <arg name=\"delta\" direction=\"in\" type=\"i\"/>\n"
    "      <arg name=\"orientation\" direction=\"in\" type=\"s\"/>\n"
    "    </method>\n"
    "    <property name=\"Category\" type=\"s\" access=\"read\"/>\n"
    "    <property name=\"Id\" type=\"s\" access=\"read\"/>\n"
    "    <property name=\"Title\" type=\"s\" access=\"read\"/>\n"
    "    <property name=\"Status\" type=\"s\" access=\"read\"/>\n"
    "    <property name=\"WindowId\" type=\"u\" access=\"read\"/>\n"
    "    <property name=\"IconName\" type=\"s\" access=\"read\"/>\n"
    "    <property name=\"IconThemePath\" type=\"s\" access=\"read\"/>\n"
    "    <property name=\"ItemIsMenu\" type=\"b\" access=\"read\"/>\n"
    "    <property name=\"Menu\" type=\"o\" access=\"read\"/>\n"
    "  </interface>\n"
    "</node>\n";

static const char* DBUSMENU_INTROSPECTION_XML = 
    "<!DOCTYPE node PUBLIC \"-//freedesktop//DTD D-BUS Object Introspection 1.0//EN\" "
    "\"http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd\">\n"
    "<node>\n"
    "  <interface name=\"org.freedesktop.DBus.Introspectable\">\n"
    "    <method name=\"Introspect\">\n"
    "      <arg name=\"data\" direction=\"out\" type=\"s\"/>\n"
    "    </method>\n"
    "  </interface>\n"
    "  <interface name=\"com.canonical.dbusmenu\">\n"
    "    <property name=\"Version\" type=\"u\" access=\"read\"/>\n"
    "    <property name=\"Status\" type=\"s\" access=\"read\"/>\n"
    "    <method name=\"GetLayout\">\n"
    "      <arg name=\"parentId\" direction=\"in\" type=\"i\"/>\n"
    "      <arg name=\"recursionDepth\" direction=\"in\" type=\"i\"/>\n"
    "      <arg name=\"propertyNames\" direction=\"in\" type=\"as\"/>\n"
    "      <arg name=\"revision\" direction=\"out\" type=\"u\"/>\n"
    "      <arg name=\"layout\" direction=\"out\" type=\"(ia{sv}av)\"/>\n"
    "    </method>\n"
    "    <method name=\"GetGroupProperties\">\n"
    "      <arg name=\"ids\" direction=\"in\" type=\"ai\"/>\n"
    "      <arg name=\"propertyNames\" direction=\"in\" type=\"as\"/>\n"
    "      <arg name=\"properties\" direction=\"out\" type=\"a(ia{sv})\"/>\n"
    "    </method>\n"
    "    <method name=\"GetProperty\">\n"
    "      <arg name=\"id\" direction=\"in\" type=\"i\"/>\n"
    "      <arg name=\"name\" direction=\"in\" type=\"s\"/>\n"
    "      <arg name=\"value\" direction=\"out\" type=\"v\"/>\n"
    "    </method>\n"
    "    <method name=\"Event\">\n"
    "      <arg name=\"id\" direction=\"in\" type=\"i\"/>\n"
    "      <arg name=\"eventId\" direction=\"in\" type=\"s\"/>\n"
    "      <arg name=\"data\" direction=\"in\" type=\"v\"/>\n"
    "      <arg name=\"timestamp\" direction=\"in\" type=\"u\"/>\n"
    "    </method>\n"
    "    <method name=\"AboutToShow\">\n"
    "      <arg name=\"id\" direction=\"in\" type=\"i\"/>\n"
    "      <arg name=\"needUpdate\" direction=\"out\" type=\"b\"/>\n"
    "    </method>\n"
    "    <signal name=\"ItemsPropertiesUpdated\">\n"
    "      <arg name=\"updatedProps\" type=\"a(ia{sv})\"/>\n"
    "      <arg name=\"removedProps\" type=\"a(ias)\"/>\n"
    "    </signal>\n"
    "    <signal name=\"LayoutUpdated\">\n"
    "      <arg name=\"revision\" type=\"u\"/>\n"
    "      <arg name=\"parent\" type=\"i\"/>\n"
    "    </signal>\n"
    "    <signal name=\"ItemActivationRequested\">\n"
    "      <arg name=\"id\" type=\"i\"/>\n"
    "      <arg name=\"timestamp\" type=\"u\"/>\n"
    "    </signal>\n"
    "  </interface>\n"
    "</node>\n";
