name: Build RPM

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v0.7.2)'
        required: true
        default: 'v0.7.2'
      zip_url:
        description: 'URL to ZIP archive containing Linux folder'
        required: true
        default: 'https://example.com/PiozaLauncher-linux.zip'

jobs:
  build_rpm:
    runs-on: ubuntu-latest

    env:
      NAME: pioza-launcher
      DATE: ${{ github.event.head_commit.timestamp }}

    steps:
    - name: Install required packages
      run: sudo apt-get update && sudo apt-get install -y rpm unzip python3 zenity tar vulkan-utils

    - name: Download ZIP archive
      run: |
        curl -L "${{ github.event.inputs.zip_url }}" -o source.zip

    - name: Unpack ZIP archive
      run: |
        unzip source.zip -d source_unpacked

    - name: Prepare RPM build tree
      run: |
        mkdir -p rpm_build/SOURCES
        mkdir -p rpm_build/SPECS

    - name: Create source ZIP for RPM
      run: |
        # Zip just the Linux folder inside unpacked source into SOURCES
        cd source_unpacked
        zip -r "../rpm_build/SOURCES/${NAME}-${{ github.event.inputs.version }}.zip" Linux
        cd ..

    - name: Copy and prepare SPEC file
      run: |
        sed \
          -e "s/%{version}/${{ github.event.inputs.version }}/g" \
          -e "s/%{date}/$(date +'%a %b %d %Y')/g" \
          Build/Linux/rpm/PiozaLauncher.spec > rpm_build/SPECS/PiozaLauncher.spec

    - name: Build RPM package
      run: rpmbuild --define "_topdir $PWD/rpm_build" -ba rpm_build/SPECS/PiozaLauncher.spec

    - name: Upload RPM artifact
      uses: actions/upload-artifact@v3
      with:
        name: pioza-launcher-rpm
        path: rpm_build/RPMS/x86_64/*.rpm
